version: "3"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user-service
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"