server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/user-service
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: ${JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        id:
          new_generator_mappings: false
        types:
          print:
            banner: false
    show-sql: ${JPA_SHOW_SQL:false}
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    service-url:
      default-zone: http://locahost:8761/eureka
    fetch-registry: true
    register-with-eureka: true